language: python
install: "pip install -r requirements.txt"
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
script: "py.test tests"
notifications:
  irc: "chat.freenode.net#baron"
